SET @sql = IF(
  EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'projetos' AND COLUMN_NAME = 'project_code'),
  'SELECT 1',
  "ALTER TABLE projetos ADD COLUMN project_code VARCHAR(50) NOT NULL DEFAULT 'PRJ-MIGRATE'"
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'recursos' AND COLUMN_NAME = 'seniority'),
  'SELECT 1',
  "ALTER TABLE recursos ADD COLUMN seniority VARCHAR(50) DEFAULT ''"
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'recursos' AND COLUMN_NAME = 'specialties_json'),
  'SELECT 1',
  "ALTER TABLE recursos ADD COLUMN specialties_json TEXT"
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

UPDATE projetos
SET project_code = CONCAT('PRJ-', REPLACE(REPLACE(UPPER(projeto), ' ', '-'), '--', '-'))
WHERE project_code IS NULL OR project_code = '' OR project_code = 'PRJ-MIGRATE';
