create table if not exists public.business_units (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  head text default '',
  lider_tec text default '',
  lider_op text default '',
  comercial text default ''
);

insert into public.business_units (id, nome, head, lider_tec, lider_op, comercial)
values (1, 'Corporativo', 'Claudio Gonçalves', 'Flávio Costa', 'Almedson Ferreira', 'David Cunha')
on conflict (id) do nothing;

alter table public.projetos add column if not exists business_unit_id bigint;
alter table public.projetos add column if not exists business_unit_nome text default 'Corporativo';

update public.projetos
set business_unit_id = 1
where business_unit_id is null;

update public.projetos
set business_unit_nome = 'Corporativo'
where business_unit_nome is null or business_unit_nome = '';

alter table public.business_units enable row level security;

drop policy if exists "service role full access business_units" on public.business_units;
create policy "service role full access business_units"
on public.business_units
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
