alter table public.projetos
add column if not exists project_type text not null default 'Projeto';

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  business_unit_id bigint not null,
  business_unit_nome text default 'Corporativo'
);

update public.projetos
set project_type = 'Projeto'
where project_type is null or project_type = '';

alter table public.produtos enable row level security;

drop policy if exists "service role full access produtos" on public.produtos;
create policy "service role full access produtos"
on public.produtos
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
