ALTER TABLE public.projetos ADD COLUMN IF NOT EXISTS project_code text DEFAULT 'PRJ-MIGRATE';

ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS external_id text DEFAULT '';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS seniority text DEFAULT '';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS specialties_json text DEFAULT '[]';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS resource_type text DEFAULT 'work';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS initials text DEFAULT '';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS max_units numeric(6,2) DEFAULT 1;
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS standard_rate numeric(12,2) DEFAULT 0;
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS overtime_rate numeric(12,2) DEFAULT 0;
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS email text DEFAULT '';

ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS external_id text DEFAULT '';
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS wbs text DEFAULT '';
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS outline_level integer DEFAULT 1;
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0;
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS task_type text DEFAULT 'fixed_units';
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS is_milestone boolean DEFAULT false;
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS duration_minutes integer DEFAULT 0;
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS is_manual boolean DEFAULT false;
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS constraint_type text DEFAULT '';
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS constraint_date text DEFAULT '';
ALTER TABLE public.tarefas ADD COLUMN IF NOT EXISTS notes text DEFAULT '';

CREATE TABLE IF NOT EXISTS public.task_assignments (
  id bigint generated by default as identity primary key,
  task_id text not null,
  resource_id bigint,
  resource_name text default '',
  units numeric(8,4) default 1,
  work numeric(10,2) default 0,
  actual_work numeric(10,2) default 0,
  remaining_work numeric(10,2) default 0,
  cost numeric(12,2) default 0
);

CREATE TABLE IF NOT EXISTS public.task_dependencies (
  id bigint generated by default as identity primary key,
  task_id text not null,
  predecessor_task_id text not null,
  dependency_type text default 'FS',
  lag_minutes integer default 0
);

CREATE INDEX IF NOT EXISTS idx_task_assignments_task ON public.task_assignments (task_id);
CREATE INDEX IF NOT EXISTS idx_task_assignments_resource ON public.task_assignments (resource_id);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_task ON public.task_dependencies (task_id);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_predecessor ON public.task_dependencies (predecessor_task_id);
