create table if not exists public.schema_migrations (
  id bigint generated by default as identity primary key,
  filename text not null unique,
  applied_at timestamptz default now()
);

create table if not exists public.comentarios (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  project_id bigint,
  project_name text default '',
  task_id text,
  task_name text default '',
  author_user_id bigint,
  author_nome text default '',
  content text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  actor_user_id bigint,
  actor_nome text default '',
  actor_role text default '',
  project_id bigint,
  summary text default '',
  before_json jsonb,
  after_json jsonb,
  created_at timestamptz default now()
);

delete from public.task_assignments a
using public.task_assignments b
where a.id > b.id
  and a.task_id = b.task_id
  and a.resource_id = b.resource_id
  and a.resource_id is not null;

create unique index if not exists uq_task_resource_assignment on public.task_assignments (task_id, resource_id);
create index if not exists idx_comentarios_project on public.comentarios (project_id);
create index if not exists idx_comentarios_task on public.comentarios (task_id);
create index if not exists idx_comentarios_author on public.comentarios (author_user_id);
create index if not exists idx_audit_logs_project on public.audit_logs (project_id);
create index if not exists idx_audit_logs_entity on public.audit_logs (entity_type, entity_id);
create index if not exists idx_audit_logs_actor on public.audit_logs (actor_user_id);

alter table public.comentarios enable row level security;
alter table public.audit_logs enable row level security;
alter table public.schema_migrations enable row level security;

drop policy if exists "service role full access comentarios" on public.comentarios;
create policy "service role full access comentarios"
on public.comentarios
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access audit_logs" on public.audit_logs;
create policy "service role full access audit_logs"
on public.audit_logs
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access schema_migrations" on public.schema_migrations;
create policy "service role full access schema_migrations"
on public.schema_migrations
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

insert into public.schema_migrations (filename)
values ('migrate_comments_audit_supabase.sql')
on conflict (filename) do nothing;
