create table if not exists public.users (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'viewer',
  active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz default now()
);

create table if not exists public.user_project_access (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  project_id bigint not null,
  created_at timestamptz default now(),
  unique (user_id, project_id)
);

insert into public.users (id, nome, email, password_hash, role, active)
values (1, 'Administrador', 'admin@abc.local', 'abcadminseed2026:65b5afe4a56a002bd8d7470aa89dc310e32da5235858e942aece88b1e7373dba8c31150f6569937e1b24729c3d7eb0c200e8c23b28da5ed46cd58360a1be831f', 'admin', true)
on conflict (id) do nothing;

alter table public.users enable row level security;
alter table public.user_sessions enable row level security;
alter table public.user_project_access enable row level security;

drop policy if exists "service role full access users" on public.users;
create policy "service role full access users"
on public.users
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access user_sessions" on public.user_sessions;
create policy "service role full access user_sessions"
on public.user_sessions
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access user_project_access" on public.user_project_access;
create policy "service role full access user_project_access"
on public.user_project_access
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
