-- ============================================
-- ABC Project Manager - Supabase/Postgres Schema
-- Execute este script no SQL Editor do Supabase
-- ============================================

create table if not exists public.recursos (
  id bigint generated by default as identity primary key,
  external_id text default '',
  nome text not null,
  funcao text default '',
  seniority text default '',
  specialties_json text default '[]',
  resource_type text default 'work',
  initials text default '',
  max_units numeric(6,2) default 1,
  standard_rate numeric(12,2) default 0,
  overtime_rate numeric(12,2) default 0,
  email text default ''
);

create table if not exists public.business_units (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  head text default '',
  lider_tec text default '',
  lider_op text default '',
  comercial text default ''
);

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  business_unit_id bigint not null,
  business_unit_nome text default 'Corporativo'
);

insert into public.business_units (id, nome, head, lider_tec, lider_op, comercial)
values (1, 'Corporativo', 'Claudio Gonçalves', 'Flávio Costa', 'Almedson Ferreira', 'David Cunha')
on conflict (id) do nothing;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'viewer',
  resource_id bigint,
  active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz default now()
);

create table if not exists public.user_project_access (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  project_id bigint not null,
  created_at timestamptz default now(),
  unique (user_id, project_id)
);

create table if not exists public.schema_migrations (
  id bigint generated by default as identity primary key,
  filename text not null unique,
  applied_at timestamptz default now()
);

insert into public.users (id, nome, email, password_hash, role, active)
values (1, 'Administrador', 'admin@abc.local', 'abcadminseed2026:65b5afe4a56a002bd8d7470aa89dc310e32da5235858e942aece88b1e7373dba8c31150f6569937e1b24729c3d7eb0c200e8c23b28da5ed46cd58360a1be831f', 'admin', true)
on conflict (id) do nothing;

create table if not exists public.projetos (
  id bigint generated by default as identity primary key,
  project_code text not null unique,
  project_type text not null default 'Projeto',
  business_unit_id bigint,
  business_unit_nome text default 'Corporativo',
  produto_id bigint,
  produto_nome text default '',
  projeto text not null,
  descricao text default '',
  prioridade text default '2- Média',
  responsavel text default '',
  ftes numeric(5,2) default 0,
  valor_previsto numeric(12,2) default 0,
  valor_gasto numeric(12,2) default 0,
  data_inicio_planej text default '',
  data_inicio_planej_date date,
  data_fim_planej text default '',
  data_fim_planej_date date,
  data_inicio text default '',
  data_inicio_real_date date,
  data_fim_real text default '',
  data_fim_real_date date,
  total_tarefas integer default 0,
  tarefas_concluidas integer default 0,
  tarefas_andamento integer default 0,
  tarefas_atrasadas integer default 0,
  tarefas_nao_iniciadas integer default 0,
  status text default '',
  conclusao numeric(5,2) default 0
);

create table if not exists public.tarefas (
  id text primary key,
  parent_id text,
  external_id text default '',
  wbs text default '',
  outline_level integer default 1,
  sort_order integer default 0,
  projeto text not null,
  tarefa text default '',
  subtarefa text default '',
  responsavel text default '',
  funcao text default '',
  data_inicio_planej text default '',
  data_inicio_planej_date date,
  esforco_planej numeric(8,2) default 0,
  data_fim_planej text default '',
  data_fim_planej_date date,
  data_inicio_real text default '',
  data_inicio_real_date date,
  esforco_real numeric(8,2) default 0,
  data_fim_real text default '',
  data_fim_real_date date,
  percentual numeric(5,2) default 0,
  status text default '',
  task_type text default 'fixed_units',
  is_milestone boolean default false,
  duration_minutes integer default 0,
  is_manual boolean default false,
  constraint_type text default '',
  constraint_date text default '',
  constraint_date_date date,
  notes text default '',
  valor_previsto numeric(12,2) default 0,
  valor_gasto numeric(12,2) default 0,
  dias_planejados integer default 0,
  dias_real integer default 0,
  dias_completados integer default 0
);

create table if not exists public.task_assignments (
  id bigint generated by default as identity primary key,
  task_id text not null,
  resource_id bigint,
  resource_name text default '',
  units numeric(8,4) default 1,
  work numeric(10,2) default 0,
  actual_work numeric(10,2) default 0,
  remaining_work numeric(10,2) default 0,
  cost numeric(12,2) default 0
);

create table if not exists public.task_dependencies (
  id bigint generated by default as identity primary key,
  task_id text not null,
  predecessor_task_id text not null,
  dependency_type text default 'FS',
  lag_minutes integer default 0
);

create table if not exists public.comentarios (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  project_id bigint,
  project_name text default '',
  task_id text,
  task_name text default '',
  author_user_id bigint,
  author_nome text default '',
  content text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  actor_user_id bigint,
  actor_nome text default '',
  actor_role text default '',
  project_id bigint,
  summary text default '',
  before_json jsonb,
  after_json jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_tarefas_parent_id on public.tarefas (parent_id);
create index if not exists idx_tarefas_projeto on public.tarefas (projeto);
create index if not exists idx_tarefas_wbs on public.tarefas (wbs);
create index if not exists idx_projetos_data_inicio_planej_date on public.projetos (data_inicio_planej_date);
create index if not exists idx_projetos_data_fim_planej_date on public.projetos (data_fim_planej_date);
create index if not exists idx_tarefas_data_inicio_planej_date on public.tarefas (data_inicio_planej_date);
create index if not exists idx_tarefas_data_fim_planej_date on public.tarefas (data_fim_planej_date);
create index if not exists idx_tarefas_constraint_date_date on public.tarefas (constraint_date_date);
create index if not exists idx_task_assignments_task on public.task_assignments (task_id);
create index if not exists idx_task_assignments_resource on public.task_assignments (resource_id);
create index if not exists idx_task_dependencies_task on public.task_dependencies (task_id);
create index if not exists idx_task_dependencies_predecessor on public.task_dependencies (predecessor_task_id);
create unique index if not exists uq_task_resource_assignment on public.task_assignments (task_id, resource_id);
create index if not exists idx_comentarios_project on public.comentarios (project_id);
create index if not exists idx_comentarios_task on public.comentarios (task_id);
create index if not exists idx_comentarios_author on public.comentarios (author_user_id);
create index if not exists idx_audit_logs_project on public.audit_logs (project_id);
create index if not exists idx_audit_logs_entity on public.audit_logs (entity_type, entity_id);
create index if not exists idx_audit_logs_actor on public.audit_logs (actor_user_id);

alter table public.recursos enable row level security;
alter table public.business_units enable row level security;
alter table public.produtos enable row level security;
alter table public.users enable row level security;
alter table public.user_sessions enable row level security;
alter table public.user_project_access enable row level security;
alter table public.projetos enable row level security;
alter table public.tarefas enable row level security;
alter table public.task_assignments enable row level security;
alter table public.task_dependencies enable row level security;
alter table public.comentarios enable row level security;
alter table public.audit_logs enable row level security;
alter table public.schema_migrations enable row level security;

drop policy if exists "service role full access recursos" on public.recursos;
create policy "service role full access recursos"
on public.recursos
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access users" on public.users;
create policy "service role full access users"
on public.users
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access user_sessions" on public.user_sessions;
create policy "service role full access user_sessions"
on public.user_sessions
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access user_project_access" on public.user_project_access;
create policy "service role full access user_project_access"
on public.user_project_access
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access business_units" on public.business_units;
create policy "service role full access business_units"
on public.business_units
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access produtos" on public.produtos;
create policy "service role full access produtos"
on public.produtos
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access projetos" on public.projetos;
create policy "service role full access projetos"
on public.projetos
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access tarefas" on public.tarefas;
create policy "service role full access tarefas"
on public.tarefas
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access task_assignments" on public.task_assignments;
create policy "service role full access task_assignments"
on public.task_assignments
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access task_dependencies" on public.task_dependencies;
create policy "service role full access task_dependencies"
on public.task_dependencies
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access comentarios" on public.comentarios;
create policy "service role full access comentarios"
on public.comentarios
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access audit_logs" on public.audit_logs;
create policy "service role full access audit_logs"
on public.audit_logs
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role full access schema_migrations" on public.schema_migrations;
create policy "service role full access schema_migrations"
on public.schema_migrations
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'fk_produtos_business_unit') then
    alter table public.produtos add constraint fk_produtos_business_unit foreign key (business_unit_id) references public.business_units(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'fk_projetos_business_unit') then
    alter table public.projetos add constraint fk_projetos_business_unit foreign key (business_unit_id) references public.business_units(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'fk_projetos_produto') then
    alter table public.projetos add constraint fk_projetos_produto foreign key (produto_id) references public.produtos(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'fk_users_resource') then
    alter table public.users add constraint fk_users_resource foreign key (resource_id) references public.recursos(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'fk_user_project_access_project') then
    alter table public.user_project_access add constraint fk_user_project_access_project foreign key (project_id) references public.projetos(id) on delete cascade;
  end if;
end $$;
