CREATE TABLE IF NOT EXISTS project_baselines (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  project_name VARCHAR(100) NOT NULL,
  project_code VARCHAR(50) NOT NULL DEFAULT '',
  baseline_number INT NOT NULL,
  baseline_name VARCHAR(160) NOT NULL,
  source_type VARCHAR(30) NOT NULL DEFAULT 'manual',
  status VARCHAR(30) NOT NULL DEFAULT 'pending_approval',
  is_official TINYINT(1) NOT NULL DEFAULT 0,
  justification TEXT,
  approval_notes TEXT,
  requested_by_user_id INT NULL,
  requested_by_nome VARCHAR(120) NOT NULL DEFAULT '',
  requested_by_role VARCHAR(20) NOT NULL DEFAULT '',
  approved_by_user_id INT NULL,
  approved_by_nome VARCHAR(120) NOT NULL DEFAULT '',
  approved_at DATETIME NULL,
  task_count INT NOT NULL DEFAULT 0,
  total_planned_effort DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_planned_cost DECIMAL(14,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_project_baseline_number (project_id, baseline_number),
  INDEX idx_project_baselines_project (project_id),
  INDEX idx_project_baselines_status (status),
  INDEX idx_project_baselines_official (project_id, is_official),
  CONSTRAINT fk_project_baselines_project FOREIGN KEY (project_id) REFERENCES projetos(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS project_baseline_tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  baseline_id INT NOT NULL,
  task_id VARCHAR(20) NOT NULL,
  task_external_id VARCHAR(50) NOT NULL DEFAULT '',
  task_wbs VARCHAR(50) NOT NULL DEFAULT '',
  parent_task_id VARCHAR(20) NULL,
  task_name VARCHAR(255) NOT NULL DEFAULT '',
  task_subtask VARCHAR(255) NOT NULL DEFAULT '',
  outline_level INT NOT NULL DEFAULT 1,
  planned_start_date DATE NULL,
  planned_finish_date DATE NULL,
  planned_effort DECIMAL(14,2) NOT NULL DEFAULT 0,
  planned_cost DECIMAL(14,2) NOT NULL DEFAULT 0,
  planned_progress DECIMAL(5,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_baseline_task_snapshot (baseline_id, task_id),
  INDEX idx_project_baseline_tasks_baseline (baseline_id),
  INDEX idx_project_baseline_tasks_wbs (task_wbs),
  CONSTRAINT fk_project_baseline_tasks_baseline FOREIGN KEY (baseline_id) REFERENCES project_baselines(id) ON DELETE CASCADE
) ENGINE=InnoDB;
