CREATE TABLE IF NOT EXISTS project_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  template_code VARCHAR(80) NOT NULL UNIQUE,
  template_name VARCHAR(180) NOT NULL,
  descricao VARCHAR(500) DEFAULT '',
  source_type VARCHAR(30) NOT NULL DEFAULT 'project_snapshot',
  source_format VARCHAR(30) NOT NULL DEFAULT 'internal_project',
  origin_project_id INT NULL,
  origin_project_name VARCHAR(180) DEFAULT '',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by_user_id INT NULL,
  created_by_name VARCHAR(120) DEFAULT '',
  created_by_role VARCHAR(20) DEFAULT '',
  total_tasks INT NOT NULL DEFAULT 0,
  total_planned_effort DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_planned_cost DECIMAL(14,2) NOT NULL DEFAULT 0,
  metadata_json JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_project_templates_origin_project (origin_project_id),
  INDEX idx_project_templates_active (is_active),
  CONSTRAINT fk_project_templates_origin_project FOREIGN KEY (origin_project_id) REFERENCES projetos(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS project_template_tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  template_id INT NOT NULL,
  template_task_key VARCHAR(80) NOT NULL,
  parent_template_task_key VARCHAR(80) DEFAULT '',
  external_id VARCHAR(50) DEFAULT '',
  wbs VARCHAR(50) DEFAULT '',
  outline_level INT DEFAULT 1,
  sort_order INT DEFAULT 0,
  tarefa VARCHAR(255) DEFAULT '',
  subtarefa VARCHAR(255) DEFAULT '',
  responsavel VARCHAR(255) DEFAULT '',
  funcao VARCHAR(100) DEFAULT '',
  data_inicio_planej VARCHAR(20) DEFAULT '',
  data_inicio_planej_date DATE NULL,
  esforco_planej DECIMAL(10,2) DEFAULT 0,
  data_fim_planej VARCHAR(20) DEFAULT '',
  data_fim_planej_date DATE NULL,
  data_inicio_real VARCHAR(20) DEFAULT '',
  data_inicio_real_date DATE NULL,
  esforco_real DECIMAL(10,2) DEFAULT 0,
  data_fim_real VARCHAR(20) DEFAULT '',
  data_fim_real_date DATE NULL,
  percentual DECIMAL(5,2) DEFAULT 0,
  status VARCHAR(30) DEFAULT '',
  task_type VARCHAR(30) DEFAULT 'fixed_units',
  is_milestone TINYINT(1) DEFAULT 0,
  duration_minutes INT DEFAULT 0,
  is_manual TINYINT(1) DEFAULT 0,
  constraint_type VARCHAR(50) DEFAULT '',
  constraint_date VARCHAR(20) DEFAULT '',
  constraint_date_date DATE NULL,
  notes TEXT,
  valor_previsto DECIMAL(14,2) DEFAULT 0,
  valor_gasto DECIMAL(14,2) DEFAULT 0,
  dias_planejados INT DEFAULT 0,
  dias_real INT DEFAULT 0,
  dias_completados INT DEFAULT 0,
  assignments_json JSON NULL,
  predecessors_json JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_project_template_task_key (template_id, template_task_key),
  INDEX idx_project_template_tasks_template (template_id),
  INDEX idx_project_template_tasks_parent_key (parent_template_task_key),
  CONSTRAINT fk_project_template_tasks_template FOREIGN KEY (template_id) REFERENCES project_templates(id) ON DELETE CASCADE
);
